ALTER TABLE Categorias ADD created_at DATETIME DEFAULT GETUTCDATE();
ALTER TABLE Categorias ADD updated_at DATETIME DEFAULT GETUTCDATE();
ALTER TABLE Subcategorias ADD created_at DATETIME DEFAULT GETUTCDATE();
ALTER TABLE Subcategorias ADD updated_at DATETIME DEFAULT GETUTCDATE();