ALTER TABLE Pedidos ADD subtotal DECIMAL(10, 2) DEFAULT 0 NOT NULL;
ALTER TABLE Pedidos ADD costo_envio DECIMAL(10, 2) DEFAULT 0 NOT NULL;
ALTER TABLE Pedidos ADD municipio NVARCHAR(100) NULL;
ALTER TABLE Pedidos ADD departamento NVARCHAR(100) NULL;
ALTER TABLE Pedidos ADD pais NVARCHAR(100) NULL;
